title: Ashutosh Chaudhary
description: My Personal Blog
author: Ashutosh Chaudhary
github: https://github.com/ashutosh2k12
about: Freelance web, apps developer
disqus_shortname: aboutashu
urls:
    - text: About Me
      url: /about/
    - text: Github
      url: https://github.com/ashutosh2k12
    - text: XML Feed
      url: /feed.xml
url: "http://aboutashu.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist